<a href="https://colab.research.google.com/github/skyil7/SejongUniv_AI/blob/master/1_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression

## Theoretical Overview
$$ H(x) = Wx +b$$

$$ cost(W, b) = \frac{1}{m} \sum^m_{i=1} \left( H(x^{(i)}) - y^{(i)} \right)^2$$

- H(x): x값에 대한 예측
- cost(W,b): W,b에 대해 함수 H(x)의 손실값

In [0]:
import torch
import torch.optim as optim

In [2]:
torch.manual_seed(1) #시드를 고정

## Data
아래의 조건을 충족하는 Fake Data를 만들어 사용
$$ y(x) = 2x+1$$

In [0]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[3], [5], [7]])

In [4]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[3.],
        [5.],
        [7.]])
torch.Size([3, 1])


## Weight Initialization

requires_grad는 파라메터가 학습되어야 하는지를 지정한다.

In [6]:
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [7]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


## Hypothesis 설정
$$ H(x) = Wx + b $$

In [8]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


## Cost
$$ cost(W, b) = \frac{1}{m} \sum^m_{i=1} \left( H(x^{(i)}) - y^{(i)} \right)^2$$

In [9]:
print(hypothesis - y_train)

tensor([[-3.],
        [-5.],
        [-7.]], grad_fn=<SubBackward0>)


In [10]:
cost = torch.mean((hypothesis - y_train)**2)    #MSE
print(cost)

tensor(27.6667, grad_fn=<MeanBackward0>)


## Gradient Descent

In [0]:
optimizer = optim.SGD([W,b], lr=0.01)

In [0]:
optimizer.zero_grad()  # Optimizer 초기화
cost.backward()        # 구한 loss로부터 Back Prop을 통해 각 변수마다 loss에 대한 gradient 산출
optimizer.step()       # 파라메터 업데이트

In [13]:
print(W)
print(b)

tensor([0.2267], requires_grad=True)
tensor([0.1000], requires_grad=True)


## Validate Training Result

In [14]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.3267],
        [0.5533],
        [0.7800]], grad_fn=<AddBackward0>)


In [15]:
cost = torch.mean((hypothesis - y_train)**2)    #MSE
print(cost)

tensor(21.8693, grad_fn=<MeanBackward0>)


## Training
Loss가 올바르게 감소하는 것을 확인했으니, 충분히 학습시키기

In [16]:
epochs = 1000
for epoch in range(1, epochs+1):
    # Train one step
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # Calculate new cost
    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis - y_train)**2)

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f} b: {:.3f} Cost: {:.6f}'.format(epoch, epochs, W.item(), b.item(), cost.item()))

Epoch  100/1000 W: 2.035 b: 0.921 Cost: 0.000895
Epoch  200/1000 W: 2.027 b: 0.938 Cost: 0.000553
Epoch  300/1000 W: 2.021 b: 0.951 Cost: 0.000342
Epoch  400/1000 W: 2.017 b: 0.962 Cost: 0.000211
Epoch  500/1000 W: 2.013 b: 0.970 Cost: 0.000130
Epoch  600/1000 W: 2.010 b: 0.976 Cost: 0.000081
Epoch  700/1000 W: 2.008 b: 0.981 Cost: 0.000050
Epoch  800/1000 W: 2.006 b: 0.985 Cost: 0.000031
Epoch  900/1000 W: 2.005 b: 0.988 Cost: 0.000019
Epoch 1000/1000 W: 2.004 b: 0.991 Cost: 0.000012


## Test

In [0]:
x_test = torch.FloatTensor([[5], [7], [10]])
y_test = torch.FloatTensor([[11], [15], [21]])

In [18]:
hypothesis = W * x_test + b
cost = torch.mean((hypothesis - y_test)**2)

print(hypothesis)
print('Cost:',cost)

tensor([[11.0109],
        [15.0188],
        [21.0308]], grad_fn=<AddBackward0>)
Cost: tensor(0.0005, grad_fn=<MeanBackward0>)
