# Logistic Regression

## Hypothesis
$$ H(X) = \frac{1}{1+e^{-WX}} $$

## Cost
$$ cost(W) = -\frac{1}{m}\Sigma ylog(H(x)) + (1 - y)(log(1 - H(x)) $$
- $Log$ loss for binary classification
  - If $ y \simeq H(x)$, cost converges to 0.
  - If $ y \neq H(x)$, cost converges to $\infty$

## Weight Update via Gradient Descent
$$ W := W - lr\cdot \frac{\partial}{\partial W}cost(W)$$

# Prepare Data

In [1]:
import torch
import torch.optim as optim

torch.manual_seed(1)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train)
print(x_train.shape)
print(y_train.shape)

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
torch.Size([6, 2])
torch.Size([6, 1])


# Train Model

In [2]:
W = torch.ones((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=1)

epochs = 1000
for epoch in range(epochs + 1):
    # Calculate Cost
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = -(y_train * torch.log(hypothesis) +
             (1 - y_train) * torch.log(1 - hypothesis)).mean()
    
    # Train
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, epochs, cost.item()
        ))

Epoch    0/1000 Cost: 2.012506
Epoch  100/1000 Cost: 0.131138
Epoch  200/1000 Cost: 0.079377
Epoch  300/1000 Cost: 0.057256
Epoch  400/1000 Cost: 0.044908
Epoch  500/1000 Cost: 0.036998
Epoch  600/1000 Cost: 0.031483
Epoch  700/1000 Cost: 0.027413
Epoch  800/1000 Cost: 0.024282
Epoch  900/1000 Cost: 0.021798
Epoch 1000/1000 Cost: 0.019778


# Evaluate Model

In [3]:
hypothesis = torch.sigmoid(x_train.mm(W) + b)

prediction = hypothesis >= torch.FloatTensor([0.5]) # T가 0.5보다 크거나 같으면 True, 아니면 False
print(prediction)

correct_prediction = prediction.float() == y_train  # T를 1.0, 0.0 으로 바꾼 다음 Y와 비교.
print(correct_prediction)

tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])
tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True]])


In [4]:
accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))

The model has an accuracy of 100.00% for the training set.


In [5]:
XX = [[100, 5]]
xx = torch.FloatTensor(XX);
hypothesis = torch.sigmoid(xx.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[True]])
