# Multi-Class Classification
클래스가 3개 이상인 경우 Softmax 함수를 이용하여 분류

## Load Data

In [1]:
import torch
import torch.optim as optim

torch.manual_seed(1)

x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]

x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

print(x_train[:5])
print(y_train[:5])

tensor([[1., 2., 1., 1.],
        [2., 1., 3., 2.],
        [3., 1., 3., 4.],
        [4., 1., 5., 5.],
        [1., 7., 5., 5.]])
tensor([2, 2, 2, 1, 1])


## one-hot encoding

In [2]:
print(y_train)
print(y_train.shape)
print(y_train.unsqueeze(1)) # unsqueeze 함수는 인수로 받은 위치에 새로운 차원을 삽입한다.
print(y_train.unsqueeze(1).shape)

nb_class = 3
nb_data = len(y_train)
y_one_hot = torch.zeros(nb_data, nb_class)
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)  # scatter(a,b,c): dimension a 에 대해 b에서 지정한 위치에 c 삽입
                                                # 언더바(_)를 함수뒤에 붙이면 in-place operation, 바꿔치기 연산이 되는데, 연산의 결과를 바로 y_one_hot에 저장하는 것이다.
                                                # (y_one_hot = y_one_hot.scatter.... 할 필요없이)

print(y_one_hot)

tensor([2, 2, 2, 1, 1, 1, 0, 0])
torch.Size([8])
tensor([[2],
        [2],
        [2],
        [1],
        [1],
        [1],
        [0],
        [0]])
torch.Size([8, 1])
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


## Train Model

In [3]:
import torch.nn.functional as F # softmax가 포함된 클래스

W = torch.zeros((4, nb_class), requires_grad=True) # 3개의 클래스에 대한 4개의 Feature별 가중치
b = torch.zeros(nb_class, requires_grad=True) # 편향은 하나만 써도 되고 클래스 갯수만큼 써도 됨

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)
nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산 (1)
    hypothesis = F.softmax(x_train.matmul(W) + b, dim=1) # or .mm or @
    
    # cost 표현번 1번 예시
    # one-hot 인코딩이 되어있고, Cross Entropy를 직접 구현
    cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
    
    # cost 표현법 2번 예시
    # torch.nn.functional에 포함된 cross entropy 사용
    # F.cross_entropy를 사용하면 scatter 함수를 이용한 one_hot_encoding을 안해도 됨
    # cost = F.cross_entropy((x_train.matmul(W) + b), y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 1.098612
Epoch  100/1000 Cost: 0.825978
Epoch  200/1000 Cost: 0.745367
Epoch  300/1000 Cost: 0.695094
Epoch  400/1000 Cost: 0.658135
Epoch  500/1000 Cost: 0.629088
Epoch  600/1000 Cost: 0.605386
Epoch  700/1000 Cost: 0.585531
Epoch  800/1000 Cost: 0.568553
Epoch  900/1000 Cost: 0.553787
Epoch 1000/1000 Cost: 0.540759


## Evaluate Model

In [4]:
# 학습된 W,b를 통한 클래스 예측
hypothesis = F.softmax(x_train.matmul(W) + b, dim=1) # or .mm or @
predict = torch.argmax(hypothesis, dim=1) # 가장 큰 값의 인덱스 출력

print(hypothesis)
print(predict)
print(y_train)


# 정확도 계산 
correct_prediction = predict.float() == y_train
print(correct_prediction)
accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))

tensor([[0.0808, 0.1519, 0.7673],
        [0.0561, 0.2938, 0.6502],
        [0.0169, 0.4154, 0.5677],
        [0.0107, 0.5506, 0.4387],
        [0.6195, 0.3130, 0.0675],
        [0.2591, 0.7232, 0.0178],
        [0.5794, 0.3999, 0.0206],
        [0.6471, 0.3453, 0.0075]], grad_fn=<SoftmaxBackward>)
tensor([2, 2, 2, 1, 0, 1, 0, 0], grad_fn=<NotImplemented>)
tensor([2, 2, 2, 1, 1, 1, 0, 0])
tensor([ True,  True,  True,  True, False,  True,  True,  True])
The model has an accuracy of 87.50% for the training set.
